# Mapeo de palabras clave → (categoria, subcategoria)
# Compatible con la estructura de gastos de la app React Native

KEYWORD_MAP = {
    # ── Hogar ──────────────────────────────────────────────────────────────────
    'arriendo':         ('hogar', 'arriendo'),
    'alquiler':         ('hogar', 'arriendo'),
    'renta':            ('hogar', 'arriendo'),
    'administracion':   ('hogar', 'administracion'),
    'administración':   ('hogar', 'administracion'),
    'admin':            ('hogar', 'administracion'),
    'luz':              ('hogar', 'luz'),
    'electricidad':     ('hogar', 'luz'),
    'enel':             ('hogar', 'luz'),
    'codensa':          ('hogar', 'luz'),
    'agua':             ('hogar', 'agua'),
    'acueducto':        ('hogar', 'agua'),
    'gas':              ('hogar', 'gas'),
    'surtigas':         ('hogar', 'gas'),
    'telefono':         ('hogar', 'telefono'),
    'teléfono':         ('hogar', 'telefono'),
    'celular':          ('hogar', 'telefono'),
    'claro':            ('hogar', 'telefono'),
    'movistar':         ('hogar', 'telefono'),
    'tigo':             ('hogar', 'telefono'),
    'wom':              ('hogar', 'telefono'),
    'internet':         ('hogar', 'internet'),
    'wifi':             ('hogar', 'internet'),
    'cable':            ('hogar', 'tv'),
    'television':       ('hogar', 'tv'),
    'televisión':       ('hogar', 'tv'),
    'tv':               ('hogar', 'tv'),

    # ── Comida ─────────────────────────────────────────────────────────────────
    'mercado':          ('comida', 'mercado'),
    'supermercado':     ('comida', 'mercado'),
    'exito':            ('comida', 'mercado'),
    'éxito':            ('comida', 'mercado'),
    'carulla':          ('comida', 'mercado'),
    'jumbo':            ('comida', 'mercado'),
    'd1':               ('comida', 'mercado'),
    'ara':              ('comida', 'mercado'),
    'lider':            ('comida', 'mercado'),
    'líder':            ('comida', 'mercado'),
    'almuerzo':         ('comida', 'comidasFuera'),
    'desayuno':         ('comida', 'comidasFuera'),
    'cena':             ('comida', 'comidasFuera'),
    'comida':           ('comida', 'comidasFuera'),
    'restaurant':       ('comida', 'comidasFuera'),
    'restaurante':      ('comida', 'comidasFuera'),
    'domicilio':        ('comida', 'comidasFuera'),
    'rappi':            ('comida', 'comidasFuera'),
    'ifood':            ('comida', 'comidasFuera'),
    'pedidosya':        ('comida', 'comidasFuera'),
    'mcdonald':         ('comida', 'comidasFuera'),
    'burger':           ('comida', 'comidasFuera'),
    'pizza':            ('comida', 'comidasFuera'),
    'cafe':             ('comida', 'comidasFuera'),
    'café':             ('comida', 'comidasFuera'),
    'tinto':            ('comida', 'comidasFuera'),
    'onces':            ('comida', 'comidasFuera'),
    'snack':            ('comida', 'comidasFuera'),

    # ── Transporte ─────────────────────────────────────────────────────────────
    'gasolina':                 ('transporte', 'gasolina'),
    'combustible':              ('transporte', 'gasolina'),
    'taxi':                     ('transporte', 'taxiUber'),
    'uber':                     ('transporte', 'taxiUber'),
    'indriver':                 ('transporte', 'taxiUber'),
    'beat':                     ('transporte', 'taxiUber'),
    'cabify':                   ('transporte', 'taxiUber'),
    'transporte publico':       ('transporte', 'transportePublico'),
    'transporte público':       ('transporte', 'transportePublico'),
    'buseta':                   ('transporte', 'transportePublico'),
    'colectivo':                ('transporte', 'transportePublico'),
    'pasaje':                   ('transporte', 'transportePublico'),
    'bus':                      ('transporte', 'transportePublico'),
    'metroplus':                ('transporte', 'metro'),
    'metro plus':               ('transporte', 'metro'),
    'tranvia':                  ('transporte', 'metro'),
    'tranvía':                  ('transporte', 'metro'),
    'metro':                    ('transporte', 'metro'),
    'mantenimiento':            ('transporte', 'mantenimientoAuto'),
    'mecanico':                 ('transporte', 'mantenimientoAuto'),
    'mecánico':                 ('transporte', 'mantenimientoAuto'),
    'aceite':                   ('transporte', 'mantenimientoAuto'),
    'lavadero':                 ('transporte', 'mantenimientoAuto'),
    'soat':                     ('transporte', 'seguroAuto'),
    'peaje':                    ('transporte', 'taxiUber'),
    'parqueadero':              ('transporte', 'taxiUber'),
    'parking':                  ('transporte', 'taxiUber'),

    # ── Créditos ───────────────────────────────────────────────────────────────
    'hipoteca':         ('creditos', 'creditoHipotecario'),
    'hipotecario':      ('creditos', 'creditoHipotecario'),
    'credito hipotecario': ('creditos', 'creditoHipotecario'),
    'crédito hipotecario': ('creditos', 'creditoHipotecario'),
    'credito auto':     ('creditos', 'creditoAuto'),
    'crédito auto':     ('creditos', 'creditoAuto'),
    'credito carro':    ('creditos', 'creditoAuto'),
    'crédito carro':    ('creditos', 'creditoAuto'),
    'tarjeta':          ('creditos', 'tarjetaCredito'),
    'visa':             ('creditos', 'tarjetaCredito'),
    'mastercard':       ('creditos', 'tarjetaCredito'),
    'cuota':            ('creditos', 'tarjetaCredito'),
    'credito':          ('creditos', 'otro'),
    'crédito':          ('creditos', 'otro'),
    'prestamo':         ('creditos', 'otro'),
    'préstamo':         ('creditos', 'otro'),

    # ── Entretenimiento ────────────────────────────────────────────────────────
    'inteligencia artificial': ('entretenimiento', 'ia'),
    'apple music':      ('entretenimiento', 'appleMusic'),
    'applemusic':       ('entretenimiento', 'appleMusic'),
    'chatgpt':          ('entretenimiento', 'ia'),
    'midjourney':       ('entretenimiento', 'ia'),
    'openai':           ('entretenimiento', 'ia'),
    'copilot':          ('entretenimiento', 'ia'),
    'claude':           ('entretenimiento', 'ia'),
    'viaje':            ('entretenimiento', 'viajes'),
    'viajes':           ('entretenimiento', 'viajes'),
    'vuelo':            ('entretenimiento', 'viajes'),
    'hotel':            ('entretenimiento', 'viajes'),
    'airbnb':           ('entretenimiento', 'viajes'),
    'rumba':            ('entretenimiento', 'fiesta'),
    'fiesta':           ('entretenimiento', 'fiesta'),
    'bar':              ('entretenimiento', 'diversion'),
    'cine':             ('entretenimiento', 'diversion'),
    'pelicula':         ('entretenimiento', 'diversion'),
    'película':         ('entretenimiento', 'diversion'),
    'concierto':        ('entretenimiento', 'diversion'),
    'evento':           ('entretenimiento', 'diversion'),
    'steam':            ('entretenimiento', 'diversion'),
    'ia':               ('entretenimiento', 'ia'),

    # ── Familia / Suscripciones ────────────────────────────────────────────────
    'colegio':          ('familia', 'colegios'),
    'colegiatura':      ('familia', 'colegios'),
    'pension':          ('familia', 'colegios'),
    'pensión':          ('familia', 'colegios'),
    'medicina':         ('familia', 'seguroMedico'),
    'eps':              ('familia', 'seguroMedico'),
    'medicamento':      ('familia', 'seguroMedico'),
    'farmacia':         ('familia', 'seguroMedico'),
    'drogueria':        ('familia', 'seguroMedico'),
    'droguería':        ('familia', 'seguroMedico'),
    'netflix':          ('familia', 'suscripciones'),
    'spotify':          ('familia', 'suscripciones'),
    'youtube':          ('familia', 'suscripciones'),
    'amazon':           ('familia', 'suscripciones'),
    'disney':           ('familia', 'suscripciones'),
    'hbo':              ('familia', 'suscripciones'),
    'apple':            ('familia', 'suscripciones'),
    'suscripcion':      ('familia', 'suscripciones'),
    'suscripción':      ('familia', 'suscripciones'),
    'gimnasio':         ('familia', 'gimnasio'),
    'gym':              ('familia', 'gimnasio'),
    'impuesto':         ('familia', 'impuestos'),
    'dian':             ('familia', 'impuestos'),
    'predial':          ('familia', 'impuestos'),

    # ── Ingresos ───────────────────────────────────────────────────────────────
    'salario':          ('ingresos', 'salario'),
    'sueldo':           ('ingresos', 'salario'),
    'pago':             ('ingresos', 'salario'),
    'quincena':         ('ingresos', 'salario'),
    'nomina':           ('ingresos', 'salario'),
    'nómina':           ('ingresos', 'salario'),
    'bono':             ('ingresos', 'bonos'),
    'prima':            ('ingresos', 'bonos'),
    'comision':         ('ingresos', 'comisiones'),
    'comisión':         ('ingresos', 'comisiones'),
    'dividendo':        ('ingresos', 'dividendos'),
    'freelance':        ('ingresos', 'otros'),
    'venta':            ('ingresos', 'otros'),
}

# Palabras que indican explícitamente que es un INGRESO
INGRESO_KEYWORDS = {
    'salario', 'sueldo', 'pago', 'quincena', 'nomina', 'nómina',
    'bono', 'prima', 'comision', 'comisión', 'dividendo', 'freelance',
    'venta', 'gané', 'gane', 'ingreso', 'cobré', 'cobre', 'recibí', 'recibi',
    'me pagaron', 'pagaron',
}

# Etiquetas legibles para la UI del bot
CATEGORY_LABELS = {
    'hogar':            'Hogar',
    'comida':           'Comida',
    'transporte':       'Transporte',
    'creditos':         'Créditos',
    'entretenimiento':  'Entretenimiento',
    'familia':          'Familia',
    'ingresos':         'Ingresos',
    'otro':             'Otro',
}

SUBCATEGORY_LABELS = {
    'arriendo':             'Arriendo',
    'administracion':       'Administración',
    'luz':                  'Luz',
    'agua':                 'Agua',
    'gas':                  'Gas',
    'telefono':             'Teléfono',
    'internet':             'Internet',
    'tv':                   'TV / Cable',
    'mercado':              'Mercado',
    'comidasFuera':         'Comidas fuera',
    'gasolina':             'Gasolina',
    'taxiUber':             'Taxi / Uber',
    'transportePublico':    'Transporte público',
    'metro':                'Metro',
    'mantenimientoAuto':    'Mantenimiento auto',
    'seguroAuto':           'Seguro auto',
    'creditoHipotecario':   'Crédito hipotecario',
    'creditoAuto':          'Crédito auto',
    'tarjetaCredito':       'Tarjeta de crédito',
    'viajes':               'Viajes',
    'restaurantes':         'Restaurantes',
    'diversion':            'Diversión',
    'fiesta':               'Fiesta',
    'appleMusic':           'Apple Music',
    'ia':                   'IA / Inteligencia Artificial',
    'colegios':             'Colegio',
    'seguroMedico':         'Seguro médico',
    'otrosSeguros':         'Otros seguros',
    'suscripciones':        'Suscripciones',
    'gimnasio':             'Gimnasio',
    'impuestos':            'Impuestos',
    'salario':              'Salario',
    'bonos':                'Bonos / Prima',
    'comisiones':           'Comisiones',
    'dividendos':           'Dividendos',
    'extraordinario':       'Extraordinario',
    'otros':                'Otros',
    'otro':                 'Otro',
}
